export const SET_LINKS = "SET_LINKS"
export const GET_LINKS = "GET_LINKS"
export const DELETE_LINK = "DELETE_LINK"

export const SET_LAST_CREATED_LINK = "SET_LAST_CREATED_LINK"

export const GET_DOWNLOAD_LINK = "GET_DOWNLOAD_LINK"
export const SET_DOWNLOAD_LINK = "SET_DOWNLOAD_LINK"

export const DOWNLOAD_FILE = "DOWNLOAD_FILE"
export const DOWNLOAD_OR_OPEN_FILE = "DOWNLOAD_OR_OPEN_FILE"
export const DOWNLOAD_FOLDER = "DOWNLOAD_FOLDER"

export const UPLOAD_FILES = "UPLOAD_FILES"

export const SET_ERROR = "SET_ERROR"
export const SET_LOADING = "SET_LOADING"